server:
  port: 8080
  tomcat:
    connection-timeout: -1
    keep-alive-timeout: -1

spring:
  application:
    name: opster-backend
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:opster.db
    username: 
    password: 

  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  
  # Spring AI Alibaba Configuration
  ai:
    dashscope:
      api-key: xxxxx
#      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      chat:
        options:
          model: qwen-plus
        enabled: true
      embedding:
        options:
          model: text-embedding-v1
        enabled: false

opster:
  maven-home: /home/soft/apache-maven-4.0.0
  java-home: /home/soft/jdk-25.0.1
